### ISSUE TITLE
Documentation request - OUTSIDERS: 1

### ISSUE THREAD

**Issue by trumpetx** [jpxthu/EPGP-Classic#18]
I'm trying to use OUTSIDERS: 1 and I read through the code and it seemed like it should work like this:

1. Non-guilded member makes a level 1 alt in guild -- any class, any name
2. Put public note on guilded level 1 as non-guilded "Raider" member
3. EPGP picks up the alt (via public note) and uses private note for normal EPGP business

This didn't work, but I don't know of any documentation to explain how to set it up.  Any ideas?

**Comment by jpxthu** [comment]
1. Assume you have a raid member named "A" and not in your guild.
2. Choose or create an alt in guild -- any class, any name, any level. Assume "B".
3. Set alt (B)'s public guild note: `ext:A-realm`. "realm" is A's realm name.

This addon really don't have enough document or in-game guide. I will add some later. Sorry for that.

**Comment by jpxthu** [comment]
<img width="789" alt="微信截图_20200209173417" src="https://user-images.githubusercontent.com/7257466/74099961-12a77a80-4b64-11ea-9c34-5ffa84658b9d.png">
Some tips added in PR #20.

**Comment by wolfgangjt** [comment]
Is the realm name required? Also when you put the thing in the officer note, does the actual toon's name get put in the EPGP list or does the alt that you have the note on show as active?

**Comment by trumpetx** [comment]
> Is the realm name required? Also when you put the thing in the officer note, does the actual toon's name get put in the EPGP list or does the alt that you have the note on show as active?

Yes, the realm name is required in the PUBLIC note.  When you're raiding, it shows the external toon's name (similar to how an alt in the raid would show up as an alt, but display the main's #,#).

One thing to note, if you're exporting the stuff to epgp.net or epgpweb.com, the "in-guild alt" name is what is exported, but the actual external raider name will show up as the looter.

It works very well overall.

**Comment by jpxthu** [comment]
@wolfgangjt @trumpetx 
Realm name is not required now, **ONLY IF** the character is in your realm. In classic, you can not raid with character from other realm.
I did this modify months ago.

**Comment by wolfgangjt** [comment]
K I was looking, and we have someone in our raid right now Lonecinder who is not in our guild. We put in the PUBLIC notes 'Ext:Lonecinder' under an officer's bank alt. However I do not see Lonecinder on the list in /epgp standings. Am I missing something?

**Comment by jpxthu** [comment]
@wolfgangjt It should be `ext:xxx`, not `Ext`. You can modify here to let it accept `Ext`:
https://github.com/jpxthu/EPGP-Classic/blob/master/LibGuildStorage-1.2.lua#L339
``` lua
local extName = strmatch(pubNote, 'ext:%s-(%S+)%s-')
```
