### ISSUE TITLE
Feature Request: On boss kill, pop up EP award (or automate)

### ISSUE THREAD

**Issue by wolfgangjt** [jpxthu/EPGP-Classic#24]
Our raid leader mentioned that in the original EPGP addon that whenever a boss was killed, it would pop up a box to award all players an EP award.

I was wondering if (a low priority request) there would be a way to implement this sometime? Currently when people come in late, and we clear the raid and award the raid complete bonus, I have to manually go in to the officer notes to deduct the bonus for the amount of bosses they missed.

Loving the updates man! Keep up the amazing work!

**Comment by jpxthu** [comment]
Did your raid leader used DBM? Boss kill/wipe popup is working now if you installed DBM.

If you installed DBM, when you entering world (sign in or reload), you will see "EPGP: Using DBM for boss kill tracking" in chat frame. DBM and EPGP will track all bosses, include low level 5-people dungeons. You can enable Interface->EPGP->Boss->wipe and have a test in any dungeons.

**Comment by trumpetx** [comment]
This feature works for me -- popup happens after every boss pull (DBM user here)

**Comment by wolfgangjt** [comment]
I am the raid leader (in terms of who starts the raid, i use the exodus (sp?) addon that people can whisp me inv to get invited to the raid so I can afk). Our 'raid leader' is the callout/strat person. I do have DBM installed.

I will test this today after work! Thanks man! <3

**Comment by jpxthu** [comment]
@marknl helped a lot on this feature. I did some basically test and will test on BWL and TAQ (AQ40) this week. Then it will be available in next release.

@wolfgangjt

**Comment by jpxthu** [comment]
@wolfgangjt Code merged. Please wait for next release. It will come today.
