### ISSUE TITLE
Member missing

### ISSUE THREAD

**Issue by rolfmao** [jpxthu/EPGP-Classic#25]
hi! we have a problem in our guild, some of the members dont show at the addon, so they cant be awarded with ep

**Comment by trumpetx** [comment]
You probably have something in the officer note of those members -- try blanking it out and `/reload`ing.  Alternatively, change the officer note to 0,0.

**Comment by jpxthu** [comment]
1. Try what @trumpetx said.
2. Options -> Interface -> EPGP -> List Errors
3. Check if there is LUA errors of EPGP. To enable LUA errors, type "/console scriptErrors 1".

**Comment by jpxthu** [comment]
Close this issue because there is no update.
