### ISSUE TITLE
Loot History full?

### ISSUE THREAD

**Issue by Dernaus** [jpxthu/EPGP-Classic#29]
Hello we've been using your addon for a few months now and lately i get error messages that it cannot add xxx item to the log but when i look at loot history it still list the item player recived so my question is do i need to clean up old logs to make space for new ones or is there a way to increase the size of the itemlog somewhere that i missed?

**Comment by jpxthu** [comment]
Log before one month will be removed when login. I will check about the size limitation and give some choice in the next release. Sorry for bothering you and thanks for let me know this problem.

**Comment by jpxthu** [comment]
I found nothing about log limitation. It maybe some other error. Could you upload a screen shot of that error?

**Comment by Dernaus** [comment]
Hello, i can take a screenshot on our next raid as i dont have any atm.

**Comment by jpxthu** [comment]
OK

**Comment by Dernaus** [comment]
Sorry for the late respons took longer then expected to get a screenshot,

Den March 18, 2020 at 12:06 PM skrev jpxthu <notifications@github.com>:






OK

**Comment by jpxthu** [comment]
No problem. When you meet any error again, take a screen shot, and copy the whole error message. Then I will check it. Thanks.

**Comment by jpxthu** [comment]
Close this issue because there is no update.
