### ISSUE TITLE
Addon doesn't show up in Interface Options > Addons

### ISSUE THREAD

**Issue by Lizenkugle** [jpxthu/EPGP-Classic#31]
Trying to sync up my EPGP with my guild but when I click "Options" in the top right corner to sync, it EPGP doesn't show up in addons list.  Tried reloading, relogging.  restarting PC.  No luck.  Even tried loading WoW with no other addons.

**Comment by jpxthu** [comment]
I think you didn't install EPGP correctly. It should be put in WOW_folder/_classic_/interface/addon.

**Comment by Lizenkugle** [comment]
It was installed with Twitch.

**Comment by jpxthu** [comment]
This addon works on WOW Classic 1.13.4. I don't know what happened.

**Comment by wolfgangjt** [comment]
@Lizenkugle Could you double check that Twitch installed it to the correct location? Just to make sure.

**Comment by Lizenkugle** [comment]
The update you dropped yesterday fixed it. Thanks!

**Comment by jpxthu** [comment]
Good to hear that.
