### ISSUE TITLE
Question over the on boss kill trigger

### ISSUE THREAD

**Issue by wolfgangjt** [jpxthu/EPGP-Classic#32]
So I have recently stepped down as officer in my guild and have transferred loot master to another person and they are in charge of EPGP now. I told them how to set up the 'on boss kill' award, but when he enabled it, it did nothing on boss kill. He has the latest EPGP-C and DMB installed. Is there a specific role or permission they need? This was labeled as an 'officer alt' instead of 'officer', but other than that everything should have been the same. I was always on my main officer character so that may be the issue? Officer alt is able to modify officer notes.

Thanks for your hard work mang.

**Comment by jpxthu** [comment]
He need to:
1. Enable this feature
2. Be LM (master loot) or RL (not master loot)
3. DBM installed
4. Can edit officer's note

See docs here:
https://github.com/jpxthu/EPGP-Classic/blob/master/docs/boss.md

**Comment by wolfgangjt** [comment]
Ah yes, genius that explains it, he wasnt ML. gotcha

**Comment by jpxthu** [comment]
It is the most simple way to ensure only one person will receive the pop-ups of boss mass EP award and item GP award. RCLootCouncil also uses this rule. That makes Master Looter a heavy job...
