### ISSUE TITLE
Feature Request: Negative EP

### ISSUE THREAD

**Issue by bagstone** [jpxthu/EPGP-Classic#38]
I know at first this sounds like a strange feature request - why would you want negative EP. Well, we're using EPGP-Classic in conjunction with RCLC and the RCLC-EPGP Addon in DKP mode... and DKP can very well be negative (and will be at the start of AQ). In DKP mode, RCLC just uses EP as DKP (and ignores GP and PR). But right now EPGP doesn't support negative EP - if you assign someone negative values via officer note it removes the player from the roster, and the addon doesn't allow a player to go into negative EP. Would it be possible to "fix" this?

**Comment by jpxthu** [comment]
@bagstone 

Test feature, may have problems. Enable it in options -> interface -> EPGP, or type in `/epgp config`, then you can see the toggle.
You may need to set a negative BASE_GP.
