### ISSUE TITLE
On Titan toolbar error on mouseover

### ISSUE THREAD

**Issue by rbpaiett** [jpxthu/EPGP-Classic#50]
When doing mouseover on icon on the Titan toolbar I get the following error:

2x AceLocale-3.0-6: EPGP: Missing entry for 'Decay=%s%% BaseGP=%s MinEP=%s Extras=%s%%'
EPGP-Classic\modules\ldb.lua:41: in function `func'
TitanClassic\LDBToTitanClassic.lua:185: in function `TitanLDBSetTooltip'
TitanClassic\LDBToTitanClassic.lua:249: in function <TitanClassic\LDBToTitanClassic.lua:247>

Am I missing something?

**Comment by jpxthu** [comment]
https://github.com/jpxthu/EPGP-Classic/blob/master/modules/ldb.lua#L41
``` lua
L["Decay=%s%% BaseGP=%s MinEP=%s Extras=%s%%"]
```
There is no such an item in `localization`. I think there is no need to localize it. Try to modify it to a string if you are calling this file. If it works, create a PR please. Thanks!

**Comment by jpxthu** [comment]
Please try this locally: https://github.com/jpxthu/EPGP-Classic/pull/51

**Comment by rbpaiett** [comment]
Is this something I need to be doing or am I just being given the latest info?  I don't understand much about what you're talking about.

**Comment by jpxthu** [comment]
Never mind. I just released a new version. Please update and have a try when v1.5.5 is available.

**Comment by rbpaiett** [comment]
Works just fine, thanks!
