### ISSUE TITLE
/epgp ep \ gp commands dont work on RU client

### ISSUE THREAD

**Issue by brkngtho** [jpxthu/EPGP-Classic#52]
![a5SPuup](https://user-images.githubusercontent.com/73508790/97247340-8a135c00-1810-11eb-82dc-cc17db7671d5.png)

>EPGP: Ignoring EP change for unknown member %s

Character is GM

**Comment by jpxthu** [comment]
Please try `name-realm` instead of `name`. If it works, I will do a quick fix. Thanks!

**Comment by jpxthu** [comment]
Published in v1.5.7
