### ISSUE TITLE
TBC Classic support please

### ISSUE THREAD

**Issue by Heckepes** [jpxthu/EPGP-Classic#54]

**Comment by jpxthu** [comment]
I am on a business trip. I will start working on TBC support in a week. Sorry for the inconvenience.

**Comment by scarecr0w12** [comment]
Any update on this at all? Looks like all works, with the exception of auto distro of points when boss is downed or on wipe.

**Comment by jpxthu** [comment]
Updated. Please let me know if there is any problem. Sorry for the late.

**Comment by scarecr0w12** [comment]
Not seeing any of the new Raids in list while using newest version.

**Comment by jpxthu** [comment]
> Not seeing any of the new Raids in list while using newest version.

@scarecr0w12 https://github.com/marknl/LibEncounters has not updated. I don't know the full name of bosses. Please disable the auto boss award temporary.
